version: 2
jobs:
    deploy:
        docker:
            - image: circleci/node:8.10.0
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache: # Download and cache dependencies
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies- # fallback to using the latest cache if no exact match is found
            - run: npm install
            - run:
                  name: "Install Dependecies"
                  command: npm install --save-dev firebase-tools
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: "Build Client Code(react-scripts によるビルド実行)"
                  command: npm run build
            - attach_workspace:
                  at: .
            - run:
                  name: "Deploy to Hosting"
                  command: node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"

workflows:
    version: 2
    build_deploy:
        jobs:
            - deploy:
                  filters:
                      branches:
                          only: master
